project:
  type: website

website:
  title: "Blue Observer"
  search: false
  navbar:
    logo: logo.jpg
    left:
      - href: index.qmd
        text: Map
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css



